steps:
  # Build the Docker image for app2
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/csci5409kubernetesassignment/app2-repo/app2:latest', '.']
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/csci5409kubernetesassignment/app2-repo/app2:latest']
  # Authenticate with GKE cluster (fixed to us-central1-a)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'my-gke-cluster'
      - '--region'
      - 'us-central1-a'  # Corrected from us-central1
      - '--project'
      - 'csci5409kubernetesassignment'
  # Deploy app2 to GKE using kubectl
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'app2.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster'
images:
  - 'us-central1-docker.pkg.dev/csci5409kubernetesassignment/app2-repo/app2:latest'
logsBucket: 'gs://cloud-build-logs-csci5409kubernetesassignment'